### ISSUE TITLE
GetWindows10SDKVersion failed to detect Windows 10 SDK

### ISSUE THREAD

**Issue by infosia** [microsoft/CMake#12]
While I am testing [latest feature/Win10](https://github.com/Microsoft/CMake/commit/280597b84bfb624bf7f6169b3c039c83d9412d10) I have found GetWindows10SDKVersion always returns empty string on my Windows 10 Pro.
- OS Name   Microsoft Windows 10 Pro
- Version   10.0.10240 Build 10240
- Microsoft Visual Studio Community 2015 Version 14.0.23107.0 D14REL

I found that it failed at `VerifyVersionInfo`, because it seems `VerifyVersionInfo` accepts the number [_6 or 10_ depends on the Windows 10 build number](https://social.msdn.microsoft.com/Forums/windowsdesktop/en-us/6f22c643-7a33-4581-9fbb-5462c1602f8b/windows-10-getversionex). I'm not quite sure if it's a right solution or not, but I think we need to verify _10 or 6_ to detect Windows 10. 

FYI I managed to get it working locally,

``` diff
-        if (VerifyVersionInfo(&osviex,
-          VER_MAJORVERSION | VER_MINORVERSION | VER_BUILDNUMBER,
-          dwlConditionMask))
+       auto verified = VerifyVersionInfo(&osviex,
+           VER_MAJORVERSION | VER_MINORVERSION /* | VER_BUILDNUMBER */,
+           dwlConditionMask);
+       // VerifyVersionInfo could accept 10 or 6 for major version on Windows 10
+       if (!verified && osviex.dwMajorVersion == 10) {
+           osviex.dwMajorVersion = 6;
+           verified = VerifyVersionInfo(&osviex,
+               VER_MAJORVERSION | VER_MINORVERSION /* | VER_BUILDNUMBER */,
+               dwlConditionMask);
+       }
+
+        if (verified)
```

Here's a link for [the diff](https://github.com/infosia/CMake/commit/2919f821f19743141eb8a63fa6e991f0772bf5e6)

**Comment by khouzam** [comment]
Hi @infosia,

Can you try to run our release binaries and see if you have the same problem? The issue that you're seeing is most likely caused by the compatibility behavior of Windows 10 (and Windows 8 and onward). To get the code above to work properly, a manifest needs to be embedded in the executable. This is a change that has been added but requires CMake to be built again with a binary that has the change. Otherwise, when querying the version of the OS, Windows 10 will report 6.2.9200 which is the release build of Windows 8.

If you install the build from https://github.com/Microsoft/CMake/releases/tag/Win10.V1 and either run it or rebuild CMake with it, then the issue should go away.

Please confirm if that helps.

**Comment by infosia** [comment]
Hi @khouzam, I see, awesome, it works good for me! Thanks :+1:
