### ISSUE TITLE
CMAKE_CXX_STANDARD is ignored when using clang-cl

### ISSUE THREAD

**Issue by MarkIngramUK** [microsoft/CMake#73]
When setting the following flags in `CMakeSettings.json`: 
`-DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_CXX_STANDARD=17`

The `/std:c++17` isn't appended to `clang-cl`'s command line.

Even with `set(CMAKE_CXX_STANDARD 17)` in `CMakeLists.txt`, the flag still isn't correctly applied to `clang-cl`. The only way to enable the flag was explicitly with `set(CMAKE_CXX_FLAGS "/std:c++17")`.

I'm using Visual Studio 15.8.9 (CMake version 3.11.18040201-MSVC_2). If I generate a Ninja build with CMake 3.12.3 then the flag is correctly appended, so it's either been fixed in upstream, or it's unique to the Microsoft fork.

**Comment by lukka** [comment]
@MarkIngramUK could you please provide more data about this issue?
1- did you found a work around already?
2- which version of clang are you using?
3- could you provide a small repro for this?

I tried with llvm 7.0.1 and vanilla CMake 3.13.2, and I incurred into [this error](https://gitlab.kitware.com/cmake/cmake/issues/18957) which is not fixed yet nor on official llvm nor on official CMake.
How did you workaround about this issue?

By the way, we are working on making the usage of llvm better, so it will be (no ETA) definitively a supported scenario.

**Comment by MarkIngramUK** [comment]
@lukka 

1. The workaround is to set `set(CMAKE_CXX_FLAGS "/std:c++17")` in `CMakeLists.txt` which isn't ideal.
2. Clang 7.0
3. Quite possibly, I'll see what I can do.

I didn't encounter the resource file error, probably because I haven't set the resource executable, nor specified any resources.

Great to hear you're improving LLVM support. When I attempted to change the compiler in `CMakeSettings.json` I wasn't sure whether it would be supported or not, but figured it was worth a try.

**Comment by lukka** [comment]
@MarkIngramUK thanks for the info, I will try to repro it again and report back my findings. In the mean time if you can provide a repro, that is welcome too.
Regarding using other tool chain with VS and CMake, there is a [sample here](https://github.com/lukka/CppOpenGLWebAssemblyCMake) that shows how to use msvc on Windows, gcc/clang on Linux, and emscripten on either Windows and Linux with Visual Studio and CMake.

**Comment by MarkIngramUK** [comment]
I did leave out some potentially relevant information - I was opening a folder in Visual Studio, as opposed to generating a project. I've attached a reproducible project.

[VS.Clang-CL.zip](https://github.com/Microsoft/CMake/files/2898353/VS.Clang-CL.zip)

**Comment by lukka** [comment]
@MarkIngramUK it must have been fixed upstream in CMake already, because in VS 2019 Preview (that uses CMake 3.13 right now), does properly pass the "-std:c++17" flag to the compiler using your sample:

`C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1   -std:c++17`

and it does not if `"-DCMAKE_CXX_STANDARD=17"` is not provided in the CMakeSettings.json:

` C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP   /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MDd /Zi /Ob0 /Od /RTC1 /showIncludes `

Unfortunately you need to patch the local CMake bundled in VS with this [fix] to make it work with clang: (https://github.com/Microsoft/CMake/pull/72/files).

**Comment by MarkIngramUK** [comment]
Thanks @lukka , I guess this issue can be closed now.
