### ISSUE TITLE
Seriously?

### ISSUE THREAD

**Issue by acdemiralp** [microsoft/CMake#77]
I know you suffer from a company-wide Not Invented Here syndrome. But maintaining your own version of CMake is braindead practice. Especially when it is equivalent to the 3.13.x of the official branch, and hence does not actually support Visual Studio 2019 generators which have been added in 3.14.x. And you are distributing it with Visual Studio 2019. Your own CMake version, which is distributed with Visual Studio 2019, does not support Visual Studio 2019. I had to:
```
ren "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake" _CMake
mklink /d "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake" "C:\Program Files\CMake"
```
in order to replace it with my official 3.14.x instance to get cmake projects to work in Visual Studio 2019.

**Comment by lukka** [comment]
@acdemiralp thanks for the feedback. The use of a fork of CMake is due to the support some features of CMake Server mode which are not present in official CMake. Those are mainly needed for providing IntelliSense and for target discoveries to the VS IDE.
We agree with you and we do indeed collaborated with Kitware in order to have those features in the official CMake: version 3.14 onward the File based APIs provide all those information needed by the VS IDE and there is no need for a fork of CMake.

Regarding the support for Visual Studio 2019 generators, the Visual Studio 2019 Preview  indeed contains CMake 3.14 and it supports the VS 2019 generators.

Let us know if you have further feedback, thanks!

**Comment by lukka** [comment]
@acdemiralp closing this issue as resolved. Please feel free to provide more feedback about Visual Studio and its CMake integration, thanks!
