### ISSUE TITLE
cannot find -lversion

### ISSUE THREAD

**Issue by oviupstack** [microsoft/CMake#92]
Platform Ubuntu 18.04

I've installed prerequisites:
```
sudo apt install -y openssh-server build-essential gdb zip
```

I have installed the cmake from here:
```
wget chmod +x https://github.com/microsoft/CMake/releases/download/v3.16.3311152/cmake-3.16.3311152-MSVC_2-Linux-x64.sh
chmod +x cmake-3.16.3311152-MSVC_2-Linux-x64.sh
sudo ./cmake-3.16.3311152-MSVC_2-Linux-x64.sh --skip-license --prefix=/usr/local
```

And I got this error building with cmake
```
/usr/bin/ld: cannot find -lversion
collect2: error: ld returned 1 exit status
MyExe/CMakeFiles/MyExe.dir/build.make:101: recipe for target '../x64/Release/MyExe' failed
make[2]: *** [../x64/Release/MyExe] Error 1
CMakeFiles/Makefile2:136: recipe for target 'MyExe/CMakeFiles/MyExe.dir/all' failed
make[1]: *** [MyExe/CMakeFiles/MyExe.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

I can see in the link.txt this which is making use of `-lversion`
```
/usr/bin/c++  -g   CMakeFiles/MyExe.dir/stdafx.cpp.o CMakeFiles/MyExe.dir/MyExe.cpp.o  -o ../../x64/Debug/MyExe  ../../x64/Debug/libMyExeCore.a ../../x64/Debug/libCashFlowEngineReports.a -lversion 
```

what do I do wrong here?

**Comment by lukka** [comment]
@oviupstack the error looks like your Linux machine misses the libversion.a/.so file? You need to ensure you have that library installed on your building machine to get building working. Otherwise everything seems to be fine.

By the way, since this problem is not related to this repository, i think a better support would be provided on [Developer Community forum.](https://developercommunity.visualstudio.com/spaces/8/index.html).

**Comment by oviupstack** [comment]
it seems I am linking with this "version" which is not available on ubuntu. I took it out and I was able to move on.
